name: game-utils Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '05 06 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.1.4"
      - name: Test
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.1.4"
      - name: Lint
        run: make lint
